
@entryRef = 26GB999999TEST0T07
@docRef = GBCHD2026.0000047

PUT https://btms-gateway.api.dev.cdp-int.defra.cloud/ITSW/CDS/SubmitImportDocumentCDSFacadeService
User-Agent: vscode-restclient
Content-Type: application/xml

<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
    <soap:Header>
        <oas:Security soap:role="system" soap:mustUnderstand="true">
            <oas:UsernameToken>
            </oas:UsernameToken>
        </oas:Security>
    </soap:Header>
    <soap:Body>
        <ALVSClearanceRequest xmlns="http://submitimportdocumenthmrcfacade.types.esb.ws.cara.defra.com">
            <ServiceHeader>
                <SourceSystem>CDS</SourceSystem>
                <DestinationSystem>ALVS</DestinationSystem>
                <CorrelationId>355466430215</CorrelationId>
                <ServiceCallTimestamp>2026-04-02T10:00:01.001</ServiceCallTimestamp>
            </ServiceHeader>
            <Header>
                <EntryReference>{{entryRef}}</EntryReference>
                <EntryVersionNumber>1</EntryVersionNumber>
                <DeclarationUCR>4GB979990102005-0160-25</DeclarationUCR>
                <DeclarationType>S</DeclarationType>
                <SubmitterTURN>GB998038429000</SubmitterTURN>
                <DeclarantId>GB998038429000</DeclarantId>
                <DeclarantName>GB998038429000</DeclarantName>
                <DispatchCountryCode>MA</DispatchCountryCode>
                <GoodsLocationCode>DEUDEUDEU</GoodsLocationCode>
            </Header>
                <Item>
                <ItemNumber>1</ItemNumber>
                <CustomsProcedureCode>4000000</CustomsProcedureCode>
                <TaricCommodityCode>0101210000</TaricCommodityCode>
                <GoodsDescription>Horses</GoodsDescription>
                <ConsigneeId>GB991900746000</ConsigneeId>
                <ConsigneeName>GB991900746000</ConsigneeName>
                <ItemNetMass>900</ItemNetMass>
                <ItemOriginCountryCode>MA</ItemOriginCountryCode>
                <Document>
                    <DocumentCode>C640</DocumentCode>
                    <DocumentReference>{{docRef}}</DocumentReference>
                    <DocumentStatus>AE</DocumentStatus>
                    <DocumentControl>P</DocumentControl>
                </Document>
                <Check>
                    <CheckCode>H221</CheckCode>
                    <DepartmentCode>AHVLA</DepartmentCode>
                </Check>
            </Item>
         </ALVSClearanceRequest>
    </soap:Body>
</soap:Envelope>